/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Proekt;

/**
 *
 * @author Виктория Стефанова
 */
public class PlaylistOfTheDay extends javax.swing.JFrame {

    /**
     * Creates new form PlaylistOfTheDay
     */
    public PlaylistOfTheDay() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPlaylistOfTheDay = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnGeneriraiNovPlaylist = new javax.swing.JButton();
        btnIzhodOtProfil = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlPlaylistOfTheDay.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Harrington", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 204, 0));
        jLabel1.setText("Playlist of the day");

        btnGeneriraiNovPlaylist.setBackground(new java.awt.Color(255, 204, 0));
        btnGeneriraiNovPlaylist.setText("Генерирай нов плейлист");
        btnGeneriraiNovPlaylist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneriraiNovPlaylistActionPerformed(evt);
            }
        });

        btnIzhodOtProfil.setBackground(new java.awt.Color(255, 204, 0));
        btnIzhodOtProfil.setText("Изход от профил");
        btnIzhodOtProfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzhodOtProfilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPlaylistOfTheDayLayout = new javax.swing.GroupLayout(pnlPlaylistOfTheDay);
        pnlPlaylistOfTheDay.setLayout(pnlPlaylistOfTheDayLayout);
        pnlPlaylistOfTheDayLayout.setHorizontalGroup(
            pnlPlaylistOfTheDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlaylistOfTheDayLayout.createSequentialGroup()
                .addGroup(pnlPlaylistOfTheDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPlaylistOfTheDayLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPlaylistOfTheDayLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnGeneriraiNovPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnIzhodOtProfil, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        pnlPlaylistOfTheDayLayout.setVerticalGroup(
            pnlPlaylistOfTheDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPlaylistOfTheDayLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 403, Short.MAX_VALUE)
                .addGroup(pnlPlaylistOfTheDayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGeneriraiNovPlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIzhodOtProfil))
                .addGap(36, 36, 36))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPlaylistOfTheDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPlaylistOfTheDay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlPlaylistOfTheDay.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGeneriraiNovPlaylistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneriraiNovPlaylistActionPerformed
         this.dispose();
        new SportNaDenq().setVisible(true);
    }//GEN-LAST:event_btnGeneriraiNovPlaylistActionPerformed

    private void btnIzhodOtProfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzhodOtProfilActionPerformed
               this.dispose();
        new Vhod().setVisible(true);
    }//GEN-LAST:event_btnIzhodOtProfilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlaylistOfTheDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlaylistOfTheDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlaylistOfTheDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlaylistOfTheDay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlaylistOfTheDay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGeneriraiNovPlaylist;
    private javax.swing.JButton btnIzhodOtProfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel pnlPlaylistOfTheDay;
    // End of variables declaration//GEN-END:variables
}
